variables:
  IVY_CACHE_DIR: "$CI_PROJECT_DIR/.cache/ivy"
  JAVA_VERSION: 8

cache:
  key: ${JAVA_VERSION}-${CI_COMMIT_REF_SLUG}
  paths:
    - .cache/
    - tools/

build-dist:
  image: registry.gitlab.com/smocktaylor/josm/openjdk/ant:$JAVA_VERSION
  stage: deploy
  script:
    - $ANT_HOME/bin/ant -Divy.home="$IVY_CACHE_DIR" dist-optimized-report distmac distwin javadoc taginfo
  interruptible: true
  artifacts:
    public: true
    paths: ["dist"]


build-java:
  image: registry.gitlab.com/smocktaylor/josm/openjdk/ant:$JAVA_VERSION
  stage: build
  script:
    - $ANT_HOME/bin/ant -Divy.home="$IVY_CACHE_DIR" clean dist
  interruptible: true
  artifacts:
    paths:
      - "build"
      - "dist"

test-java:
  image: registry.gitlab.com/smocktaylor/josm/openjdk/ant:$JAVA_VERSION
  stage: test
  script:
    - $ANT_HOME/bin/ant -Divy.home="$IVY_CACHE_DIR" -Dtest.headless=true test test-html 1> /dev/null
  interruptible: true
  artifacts:
    public: true
    paths:
      - "test/report/jacoco.xml"
    reports:
      junit:
        - "test/report/TEST-*.xml"

coverage-java:
  stage: deploy
  image: registry.gitlab.com/haynes/jacoco2cobertura:1.0.7
  script:
    - 'python /opt/cover2cover.py test/report/jacoco.xml src > test/report/coverage.xml'
    - 'python /opt/source2filename.py test/report/coverage.xml'
  needs: ["test-java"]
  dependencies:
    - test-java
  artifacts:
    reports:
      cobertura: "test/report/coverage.xml"

navigation-java:
  stage: deploy
  image: registry.gitlab.com/smocktaylor/josm/openjdk/ant:$JAVA_VERSION
  script:
    - $ANT_HOME/bin/ant -Dlsif=true compile
    - curl -fLo coursier https://git.io/coursier-cli
    - chmod +x coursier
    - ./coursier launch com.sourcegraph:lsif-java_2.13:0.5.1 -- index-semanticdb build/semanticdb
  cache: {}
  artifacts:
    reports:
      lsif: dump.lsif

pmd-java:
  image: registry.gitlab.com/smocktaylor/josm/openjdk/ant:$JAVA_VERSION
  stage: test
  script:
    - $ANT_HOME/bin/ant -Divy.home="$IVY_CACHE_DIR" pmd
  interruptible: true
  artifacts:
    reports:
      codequality:
        - codeclimate-josm.json

checkstyle-java:
  image: registry.gitlab.com/smocktaylor/josm/openjdk/ant:$JAVA_VERSION
  stage: test
  script:
    - $ANT_HOME/bin/ant -Divy.home="$IVY_CACHE_DIR" checkstyle
  interruptible: true
  artifacts:
    public: true
    paths:
      - "checkstyle-josm.xml"

spotbugs-java:
  image: registry.gitlab.com/smocktaylor/josm/openjdk/ant:$JAVA_VERSION
  stage: test
  script:
    - $ANT_HOME/bin/ant -Divy.home="$IVY_CACHE_DIR" spotbugs
  interruptible: true
  artifacts:
    public: true
    paths:
      - "spotbugs-josm.xml"

binary-compatibility:
  image: tsmock77/japi-compliance-checker:latest
  stage: test
  script:
    - apk add curl
    - LATEST=$(curl https://josm.openstreetmap.de/latest)
    - mkdir --parent .cache
    - curl -z .cache/josm-latest.jar --output .cache/josm-latest.jar https://josm.openstreetmap.de/josm-latest.jar
    - japi-compliance-checker --lib=JOSM .cache/josm-latest.jar --v1=${LATEST} dist/josm-custom.jar --v2=${CI_COMMIT_SHA}
  interruptible: true
  needs: ["build-java"]
  artifacts:
    public: true
    paths:
      - "compat_reports"
  allow_failure:
    exit_codes:
      - 1
