variables:
  IVY_CACHE_DIR: "$CI_PROJECT_DIR/.cache/ivy"
  JAVA_VERSION: 8

cache:
  paths:
    - .cache/
    - tools/

build-dist:
  image: registry.gitlab.com/smocktaylor/josm/openjdk/ant:$JAVA_VERSION
  stage: deploy
  script:
    - $ANT_HOME/bin/ant -Divy.home="$IVY_CACHE_DIR" dist-optimized-report distmac distwin javadoc taginfo
  interruptible: true
  artifacts:
    public: true
    paths: ["build/dist/"]


build-java:
  image: registry.gitlab.com/smocktaylor/josm/openjdk/ant:$JAVA_VERSION
  stage: build
  script:
    - $ANT_HOME/bin/ant -Divy.home="$IVY_CACHE_DIR" clean dist
  interruptible: true
  artifacts:
    paths:
      - "build"

test-java:
  image: registry.gitlab.com/smocktaylor/josm/openjdk/ant:$JAVA_VERSION
  stage: test
  script:
    - $ANT_HOME/bin/ant -Divy.home="$IVY_CACHE_DIR" -Dtest.headless=true test
  interruptible: true
  artifacts:
    public: true
    paths:
      - "test/report/jacoco.xml"
    reports:
      junit:
        - "test/report/TEST-*.xml"

coverage-java:
  stage: deploy
  image: registry.gitlab.com/haynes/jacoco2cobertura:1.0.7
  script:
    - 'python /opt/cover2cover.py test/report/jacoco.xml src > test/report/coverage.xml'
    - 'python /opt/source2filename.py test/report/coverage.xml'
  needs: ["test-java"]
  dependencies:
    - test-java
  artifacts:
    reports:
      cobertura: "test/report/coverage.xml"

navigation-java:
  stage: deploy
  image: registry.gitlab.com/smocktaylor/josm/openjdk/ant:$JAVA_VERSION
  script:
    - ant -Dlsif=true compile
    - curl -fLo coursier https://git.io/coursier-cli
    - chmod +x coursier
    - ./coursier launch com.sourcegraph:lsif-java_2.13:0.5.1 -- index-semanticdb build/semanticdb
  cache: {}
  artifacts:
    reports:
      lsif: dump.lsif

pmd-java:
  image: registry.gitlab.com/smocktaylor/josm/openjdk/ant:$JAVA_VERSION
  stage: test
  script:
    - $ANT_HOME/bin/ant -Divy.home="$IVY_CACHE_DIR" pmd
  interruptible: true
  artifacts:
    reports:
      codequality:
        - codeclimate-josm.json

checkstyle-java:
  image: registry.gitlab.com/smocktaylor/josm/openjdk/ant:$JAVA_VERSION
  stage: test
  script:
    - $ANT_HOME/bin/ant -Divy.home="$IVY_CACHE_DIR" checkstyle
  interruptible: true
  artifacts:
    public: true
    paths:
      - "checkstyle-josm.xml"

spotbugs-java:
  image: registry.gitlab.com/smocktaylor/josm/openjdk/ant:$JAVA_VERSION
  stage: test
  script:
    - $ANT_HOME/bin/ant -Divy.home="$IVY_CACHE_DIR" spotbugs
  interruptible: true
  artifacts:
    public: true
    paths:
      - "spotbugs-josm.xml"
